version: '3.8'

volumes:
  postgres-data:

networks:
  watchmap:
    driver: bridge

services:
  app:
    container_name: watchmap
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - watchmap
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      PROJECT_HOST: http://localhost:3000
    depends_on:
      - db

  db:
    container_name: watchmap-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - watchmap
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"